### ISSUE TITLE
Signature not valid?

### ISSUE THREAD

**Issue by soshimee** [iamDecode/Jello#6]
Console.app says: `/Library/Application Support/MacEnhance/Plugins/Jello.bundle/Contents/MacOS/JelloInject signature not valid: -2147409652`

**Comment by iamDecode** [comment]
Yep the code signature seems to be invalidated every 6 months or so. I have updated the bundle here: https://github.com/iamDecode/Jello/releases/tag/0.0.2. Can you let me know if that bundle works for you? If so I will push an update to the macforge repositories too.

**Comment by soshimee** [comment]
Instantly works after dragging it into macforge folder, fixed!

**Comment by iamDecode** [comment]
New version submitted here: https://github.com/MacEnhance/MacForgeRepo/pull/5
